name: Auto Publish to Public Portfolio

on:
  schedule:
    - cron: '0 8 * * 5'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push ke Repo Public Portfolio
        run: |
          # Otomatis ngubah nama repo: private-praktikum-... -> praktikum-...
          PUBLIC_REPO_NAME=$(echo "${{ github.event.repository.name }}" | sed 's/^private-//')
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Hubungkan dan push ke repo public mahasiswa pakai PAT
          git remote add destination "https://x-access-token:${{ secrets.PORTFOLIO_PAT }}@github.com/${{ github.repository_owner }}/${PUBLIC_REPO_NAME}.git" || true
          git push destination main --force
          echo "Kodingan berhasil di-publish ke portofolio publik!"
